### ISSUE TITLE
Display comments according to the author or the application

### ISSUE THREAD

**Issue by abaruchi** [kytos/napps-server#10]
We have to display all comments of a given user or of given author. For exemple:

It should display all comments of \*<author_name\>:
```
GET /comments?author=<author_name>
```

It should display all comments of \<napp_name\>
```
GET /comments?napp=<napp_name>
```

**Comment by beraldoleal** [comment]
The endpoint should be `/authors/<author_name>/comments/`. But this is not so important now.
For apps, we should have `/napps/<app_name>/comments/`.

**Comment by abaruchi** [comment]
Closing this issue
