### ISSUE TITLE
Upload new napp

### ISSUE THREAD

**Issue by beraldoleal** [kytos/napps-server#12]
After user authentication and get token, the user must be able to insert new app.
The endpoint should be something like ... `POST /napps/` and the user must pass a json data.

```javascript
{'git': "github.com/projectx/nappy.git",
 'token': "982987987dsw9f789sd7f9as9f7a9df9asd9f79dsf"}
```

For now, lets support only git, on the future we can support upload of a local repository.

**Comment by abaruchi** [comment]
Need to define how to limit users permissions. Right now if the user authenticate, he can view and change napps from other users.

**Comment by abaruchi** [comment]
Also we should verify if the user is active or inactive.

**Comment by abaruchi** [comment]
Feature implemented - closing issue
