### ISSUE TITLE
New user is not working

### ISSUE THREAD

**Issue by cemsbr** [kytos/napps-server#77]
I tried the following:

http --verbose --json https://napps.kytos.io/api/users/ username=test_user email='test_email' first_name='test_name' last_name='test_last' phone='123' city='São Paulo' state='SP' country='Brazil' password="$PASSWORD"

And the server crashed. Apache log:

[Thu Feb 09 02:00:57.326931 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977] mod_wsgi (pid=23710): Exception
 occurred processing WSGI script '/usr/src/kytos/napps-server/napps-server.wsgi'.
[Thu Feb 09 02:00:57.328139 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977] Traceback (most recent call las
t):
[Thu Feb 09 02:00:57.328540 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/app.py", line 2000, in __call__
[Thu Feb 09 02:00:57.328564 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     return self.wsgi_app(enviro
n, start_response)
[Thu Feb 09 02:00:57.328592 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/app.py", line 1991, in wsgi_app
[Thu Feb 09 02:00:57.329066 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     response = self.make_respon
se(self.handle_exception(e))
[Thu Feb 09 02:00:57.329099 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/app.py", line 1567, in handle_exception
[Thu Feb 09 02:00:57.329545 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     reraise(exc_type, exc_value
, tb)
[Thu Feb 09 02:00:57.329575 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/_compat.py", line 33, in reraise
[Thu Feb 09 02:00:57.330167 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     raise value
[Thu Feb 09 02:00:57.330417 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/app.py", line 1988, in wsgi_app
[Thu Feb 09 02:00:57.330456 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     response = self.full_dispat
ch_request()
[Thu Feb 09 02:00:57.330507 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
[Thu Feb 09 02:00:57.330517 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     rv = self.handle_user_excep
tion(e)
[Thu Feb 09 02:00:57.331263 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/app.py", line 1544, in handle_user_exception
[Thu Feb 09 02:00:57.331285 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     reraise(exc_type, exc_value
, tb)
[Thu Feb 09 02:00:57.331312 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/_compat.py", line 33, in reraise
[Thu Feb 09 02:00:57.331322 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     raise value
[Thu Feb 09 02:00:57.332155 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
[Thu Feb 09 02:00:57.332179 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     rv = self.dispatch_request(
)
[Thu Feb 09 02:00:57.332206 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/local/lib/python3.
5/dist-packages/flask/app.py", line 1625, in dispatch_request
[Thu Feb 09 02:00:57.332650 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     return self.view_functions[
rule.endpoint](**req.view_args)
[Thu Feb 09 02:00:57.332680 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]   File "/usr/src/kytos/napps-se
rver/napps_server/core/decorators.py", line 19, in wrapper
[Thu Feb 09 02:00:57.332689 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977]     content = request.json()
[Thu Feb 09 02:00:57.333589 2017] [wsgi:error] [pid 23710:tid 140082708047616] [remote 177.188.195.106:35977] TypeError: 'dict' object is not
 callable

**Comment by diraol** [comment]
Fixed at 350802533eed4d6404686b59378e6564ef1e2fd9
