### ISSUE TITLE
Fix linking gravatar to the wrong user

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/napps-server#93]
One may create an account with a username which is different from the Github one. My profile picture in the NApps server shows an unknown person because it looks for it on Github.

**Comment by diraol** [comment]
Yeah, we need to improve this by letting the user upload a picture or allowing the user to choose the avatar from gravatar or github.

**Comment by beraldoleal** [comment]
Maybe we should implement auth via github. Or for now, look for avatar based on email.

**Comment by renanrodrigo** [comment]
But what if I use an email address to sign in to the NApps Server different of the one I use on Github?
Any way it happens to be done, linking to Github still feels optional to me. What if I want to upload some NApps but don't use Github. Would I have to create an account just for that?
@diraol 's suggestion of asking the user if he wants to link his account to external sites seems pretty good.

**Comment by beraldoleal** [comment]
@renanrodrigo no problem, at least your gravatar will not be somebody else. For sure we should provide multiple auth methods on the future.

**Comment by beraldoleal** [comment]
I think that we need to split this issue into 2:

1. Fix linking gravatar to wrong persons;
2. Improve auth methods on napps server;

**Comment by diraol** [comment]
I agree with @beraldoleal about splitting this issue into two. [this one and another for more auth methods].

About username/email, @renanrodrigo using the email is a better way to assure that the user gravatar, if found, is from the correct person (no one will use your email, in theory). But the username is more difficult to be sure that we are dealing with the correct user.

**Comment by beraldoleal** [comment]
@renanrodrigo progress on this ?

**Comment by renanrodrigo** [comment]
@beraldoleal I don't have access to the website, I cannot take this one.

**Comment by beraldoleal** [comment]
@renanrodrigo talk with me on irc. I will give to you the proper permissions.
